const modal = document.getElementById('Modal')
const correio = document.getElementById('task')
const close = document.getElementById('close')
correio.addEventListener('click', () => { modal.style.display = 'block'})
close.addEventListener('click', () => { modal.style.display = 'none'})